### ISSUE TITLE
[BUG] Java on macosx apple scilicon is installed as a bundle, path to java is incorrect

### ISSUE THREAD

**Issue by kdhans** [CmlLib/CmlLib.Core#101]
**Describe the bug**
When running the app, the launcher looks for the java executable in /(game directory)/(java runtime directory)/bin/java, but it needs to point to /(game directory)/(java runtime directory)/jre.bundle/Contents/Home/bin/java

Current workaround is checking if the user is using a mac with apple silicon, then performing the following code right before the process starts:
process.StartInfo.FileName = process.StartInfo.FileName.Replace("/bin/java", "/jre.bundle/Contents/Home/bin/java")

Doing this filename fix launches the app correctly on mac.

**Environment (please complete the following information):**
 - OS: macosx Sonoma 14.4.1
 - CmlLib.Core Version: 3.3.10
 - .NET version: .net6.0

**Comment by AlphaBs** [comment]
thanks for reporting thr issue. I'll test this on a real macOS device later.
