### ISSUE TITLE
Question: how i can install optifine? 

### ISSUE THREAD

**Issue by TheNewR00t** [CmlLib/CmlLib.Core#104]
![image](https://github.com/CmlLib/CmlLib.Core/assets/126024362/b24a4c35-4679-4e9a-9b30-a284b0e63046)
I get this error and from what I see it needs a file called "launcher_profiles" but I don't know how to create it manually and make it functional, does anyone know?

**Comment by AlphaBs** [comment]
just copy it from `%appdata%/.minecraft/launcher_profiles.json`. it created by Mojang's Minecraft launcher.

**Comment by Davilone32Oficial** [comment]
Yes, but I say how do I get the launcher to do it by itself?

**Comment by AlphaBs** [comment]
The contents of the launcher_profiles.json file are not important.  Hardcode the file created by the mojang launcher into the launcher and write the file as is.
