### ISSUE TITLE
[BUG] The inability to install Java automatically on Mac OS.

### ISSUE THREAD

**Issue by TaigoStudio** [CmlLib/CmlLib.Core#106]
**Describe the bug**
The inability to install Java automatically on Mac OS.
During Java installation, the file installation path has jre.bundle/Contents/Home/ in it, which does not allow copying files to the runtimes folder

**Environment (please complete the following information):**
 - OS: MacOS ARM
 - CmlLib.Core Version: latest
 - .NET version: net8

**Additional context**
https://[piston-meta.mojang.com/v1/packages/453682d6317aefaaada5e2a6ad2fe486c3aaa7ab/manifest.json](https://piston-meta.mojang.com/v1/packages/453682d6317aefaaada5e2a6ad2fe486c3aaa7ab/manifest.json)

**Comment by TaigoStudio** [comment]
Also, the manifest does not have Java 8 for Mac OS ARM, which does not allow you to run older versions. Is there anything we can do about it? Oracle has officially released a version for Mac OS ARM

**Comment by AlphaBs** [comment]
I fixed this but not tested on mac yet. can you try the latest commit on dev branch?
 56aba2d899ae48478f19fd9627e09c4393be0748

**Comment by AlphaBs** [comment]
you can specify `JavaPath` property of `MLaunchOption` when the library can't load a Java automatically.

**Comment by TaigoStudio** [comment]
<img width="962" alt="Снимок экрана 2024-06-08 в 17 54 07" src="https://github.com/CmlLib/CmlLib.Core/assets/126141594/e8314dc9-5171-471c-bd00-52d31c806564">
It doesn’t work because this part has the installation path. If you remove it, everything will work

**Comment by TaigoStudio** [comment]
<img width="709" alt="Снимок экрана 2024-06-08 в 17 56 39" src="https://github.com/CmlLib/CmlLib.Core/assets/126141594/1599b6c0-6449-44d5-a654-15e6e5596821">
Here's the code that fixes it

**Comment by AlphaBs** [comment]
Is it impossible to write a file into `jre.bundle/Content/Home/`? What error do you see? I don't understand what causes the error.

**Comment by AlphaBs** [comment]
It is normal behavior to install files into `<game>/runtime/<mac>/<java>/jre.bundle/Contents/Home/bin/java`.

The new `IMinecraftJavaPathResolver` implementation can resolve the right java binary path. 

https://github.com/CmlLib/CmlLib.Core/blob/dev/src%2FJava%2FMinecraftJavaPathResolver.cs#L48-L62

**Comment by TaigoStudio** [comment]
I didn't look to see if changing this class helped. I thought that the installation path was fixed there, so I didn't run minecraft completely. Tomorrow I'll see if Java works with the modified path

**Comment by TaigoStudio** [comment]
yes, its fixed
