### ISSUE TITLE
[BUG] Multiplayer not playable

### ISSUE THREAD

**Issue by dracocraft** [CmlLib/CmlLib.Core#108]
**Describe the bug**
When enter to the game with forge 1.16.5 (i think any version of forge of all minecraft) i cant play multiplayer, only singleplayer.

**Logs**
I dont have it but soon i will upload it.

**Environment (please complete the following information):**
 - OS: Windows (10/11)
 - CmlLib.Core Version: Nuget latest (4.0)
 - .NET version: .NET Framework 4.8 (latest)

**Comment by GamerVII-NET** [comment]
In version 1.16.5 of Minecraft, multiplayer gameplay has been disabled by Microsoft for offline accounts. This affects only this version.

Possible solution: https://github.com/fn2006/PollyMC/issues/150#issuecomment-1975249764

**Comment by TaigoStudio** [comment]
https://github.com/CmlLib/CmlLib.Core/issues/85#issuecomment-1638179729
https://github.com/CmlLib/CmlLib.Core/issues/85#issuecomment-1991441996

**Comment by AlphaBs** [comment]
easy solution: add extra JVM arguments

```csharp
var process = await launcher.InstallAndBuildProcessAsync("1.16.5", new MLaunchOption
{
    Session = MSession.CreateOfflineSession("username"),
    ExtraJvmArguments = 
    [
        MArgument.FromCommandLine("-Dminecraft.api.env=custom -Dminecraft.api.auth.host=https://invalid.invalid -Dminecraft.api.account.host=https://invalid.invalid -Dminecraft.api.session.host=https://invalid.invalid -Dminecraft.api.services.host=https://invalid.invalid"),
    ]
});t
```
