### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MehanikTMYT** [CmlLib/CmlLib.Core#109]
**Describe the bug**
Doesn't lauch on 1.21.4 neoforge 

**Logs**
no logs

**Environment (please complete the following information):**
 - OS: windows 11
 - CmlLib.Core Version: 4.0.2
 - .NET version: .NET 8.0

**Additional context**
some errors: Exception in thread "main" java.lang.ExceptionInInitializerError     at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:135)     at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:125)     at cpw.mods.jarhandling.impl.JarContentsImpl.<init>(JarContentsImpl.java:56)     at cpw.mods.jarhandling.JarContentsBuilder.build(JarContentsBuilder.java:56)     at cpw.mods.jarhandling.JarContents.of(JarContents.java:64)     at cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:122)     at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @12b0404f      at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)     at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)      at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)     at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:49)      ... 7 more

**Comment by MehanikTMYT** [comment]
my bad. after fix this error with version neoforge-21.1.8 Exception in thread "main" java.lang.module.ResolutionException: Modules org.apache.logging.log4j.slf4j and org.apache.logging.log4j.slf4j2.impl export package org.apache.logging.slf4j to module io.netty.codec    at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)    at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)    at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)    at java.base/java.lang.module.Resolver.finish(Resolver.java:380)    at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)    at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)    at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)    at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)    at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

**Comment by AlphaBs** [comment]
how did you install it? I can't find 1.21.4 neoforge-21.1.8 installer.

**Comment by AlphaBs** [comment]
I found the problem. Libraries with duplicate names should be removed when building `-cp`. This will be updated in the next version.

**Comment by AlphaBs** [comment]
fixed on 4.0.3
