### ISSUE TITLE
Versions not installing

### ISSUE THREAD

**Issue by leksevzip** [CmlLib/CmlLib.Core#111]
Minecraft Version is not installing. When it goes to `IVersion version = await launcher.GetVersionAsync(InputVersion);` program automatically exits.

Environment:
 - OS: Ubuntu 24.04
 - CmlLib.Core Version: 4.0.0
 - .NET version: 8.0.110

Code:
https://www.mediafire.com/file/cjdvagbqeg2qf35/LauncherLogic.cs/file

**Comment by leksevzip** [comment]
> Does the program throw an exception when it exits?
No, just program is exits without any exceptions and errors
> What version did you try?
I tried a c0.0.11a and 1.1. Both didnt work

**Comment by leksevzip** [comment]
I found out that, if i copy install code to a Main() function its just works fine. But if i using this code in another method it just dont want to work

**Comment by AlphaBs** [comment]
maybe you forgot to put `await` for async methods or you declared a method as `async void` instead of `async Task`.

**Comment by leksevzip** [comment]
> maybe you forgot to put `await` for async methods or you declared a method as `async void` instead of `async Task`.

Nope, all awaits and async Task are in Install() method.

**Comment by AlphaBs** [comment]
would you send me the entire code?

**Comment by leksevzip** [comment]
> would you send me the entire code?

[NanoLauncherCS.zip](https://github.com/user-attachments/files/18007681/NanoLauncherCS.zip)
Here it is.
P.S I started developing this launcher just yesterday, so here's only one function

**Comment by AlphaBs** [comment]
you should make all method calling async method also `async Task`, and put `await`.

```csharp
        public static async Task Main() {
            ConsoleUI consoleUI = new ConsoleUI();
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write("NanoLauncherCS ");
            Console.ResetColor();
            Console.Write(">> ");
            string Input = Console.ReadLine();
            await consoleUI.Commands(Input);
        }

        public async Task Commands(string input) {
            LauncherLogic launcherLogic = new LauncherLogic();
            int IndexOfSpace = input.IndexOf(' ');

            if(IndexOfSpace == -1) {
                Console.WriteLine("Invalid Args!");
                await Main();
            }

            string Command = input.Substring(0,IndexOfSpace);
            string Args = input.Substring(IndexOfSpace + 1);

            switch(Command) {
                case "install":
                    await launcherLogic.Install(Args);
                    break;
            }
        }
```

this issue is not related to the library itself.
