### ISSUE TITLE
[BUG] Crash when starting application

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [CmlLib/CmlLib.Core#114]
**Describe the bug**
Crash when CmlLib.Core.VersionLoader.MojangJsonVersionLoaderV2.getManifest calls JsonSerializer.DeserializeAsync() due to Reflection-based serialization disabled.

**Logs**
Full Stacktrace + exception description:
![image](https://github.com/user-attachments/assets/7f68e420-6c62-49b9-97ea-2474d5bc9c19)

**Environment:**
 - OS: Windows 11 (24H2 build 26100.2605)
 - CmlLib.Core Version: [e.g. 4.0.3]
 - .NET version: .NET 8.0

**Additional context**
This is being run as published to folder with "Produce single file" enabled and targeting net8.0-windows and using JetBrains Rider. Full config screenshot: 
![image](https://github.com/user-attachments/assets/69f90cf9-67f6-401a-b294-e915cddc2a17)

**Comment by AlphaBs** [comment]
currently the library doesn't support trimming. uncheck the 'trim unused assemblies' option.

**Comment by BeefyAndTheDucks** [comment]
That did the trick! Thanks!
