### ISSUE TITLE
Cannot Find Any Version (CMLlib 3.1.1.0)

### ISSUE THREAD

**Issue by AcaiBerii** [CmlLib/CmlLib.Core#14]
Hey! I'm making a launcher for modpacks and forge.
I'm adding a combo-box to the menu, and I get all versions with  the following code:

```
foreach (var item in launcher.GetAllVersions())
{
        version.Items.Add(item);
}
```

But, when I go the the GUI, everything starts with "local". I started to replace everything and convert the selection to a string. CMLLib throws an error that says "can't find 'local [versiongohere]", "can't find '[versiongohere]", or "can't find 'release [versiongohere]". Any help?

I have the launcher attached, if you do want to see if anything happened.

[Debug.zip](https://github.com/CmlLib/CmlLib.Core/files/6015434/Debug.zip)

**Comment by AlphaBs** [comment]
you have to launch with version name without version type. 
like this:

`
var versionName = [your combobox name].Text.Split(' ')[1];
~~~ = launcher.CreateProcess(versionName, [launchOption]);
`

or, add version name only: 
`
foreach (var item in launcher.GetAllVersions())
{
        version.Items.Add(item.Name);
}
`

**Comment by AcaiBerii** [comment]
thank you :)
