### ISSUE TITLE
Unity

### ISSUE THREAD

**Issue by Semen-TC** [CmlLib/CmlLib.Core#20]
Hello!  I am writing a Minecraft launcher in Unity.  I have to make an additional socket server to run minecraft.  This is a very big "crutch" in the program.  Could you please make unity support for CmlLib.Core library?

**Comment by AlphaBs** [comment]
Set API compatibility level to .NET 4.x
https://docs.unity3d.com/2019.1/Documentation/Manual/dotnetProfileSupport.html

and install cmllib package via NugetForUnity
https://github.com/GlitchEnzo/NuGetForUnity
