### ISSUE TITLE
1.17 and java16

### ISSUE THREAD

**Issue by AlphaBs** [CmlLib/CmlLib.Core#23]
Currently, MJava cannot install new java version, which is necessary for new versions like 1.17-pre.
We need new java runtime installer

**Comment by LosTigeros** [comment]
Here are the runtimes for MC:
[launchermeta.mojang.com/v1/products/java-runtime/[...]/all.json](https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json)

To check which one is required, there's `javaVersion` property in the version manifest file.

**Comment by AlphaBs** [comment]
Thank you. [JavaChecker.cs](https://github.com/CmlLib/CmlLib.Core/blob/dev/CmlLib/Core/Files/JavaChecker.cs) is added
