### ISSUE TITLE
ProgressBar on process

### ISSUE THREAD

**Issue by RehabCZ** [CmlLib/CmlLib.Core#24]
Is it possible to link progressBar to launch game process?

var launcher = new CMLauncher(path());
                var launchOption = new MLaunchOption
                {
                    MaximumRamMb = memory,
                    Session = session,
                };

                var process = launcher.CreateProcess("1.7.10", "10.13.4.1614-1.7.10", launchOption);
                
                process.Start();

**Comment by AlphaBs** [comment]
```csharp
launcher.FileChanged += (e) =>
{
    Invoke(new Action(() =>
    {
        Pb_File.Maximum = e.TotalFileCount;
        Pb_File.Value = e.ProgressedFileCount;
        //Lv_Status.Text = $"{e.FileKind.ToString()} : {e.FileName} ({e.ProgressedFileCount}/{e.TotalFileCount})";
    }));
};
launcher.ProgressChanged += (s, e) =>
{
    Invoke(new Action(() =>
    {
        Pb_Progress.Maximum = 100;
        Pb_Progress.Value = e.ProgressPercentage;
    }));
};
```

see [README](https://github.com/CmlLib/CmlLib.Core/blob/master/README.md), [Handling Events](https://github.com/CmlLib/CmlLib.Core/wiki/Handling-Events)
