### ISSUE TITLE
Forge Versions

### ISSUE THREAD

**Issue by KubaTMofficial** [CmlLib/CmlLib.Core#30]
Where can I check what to type in versions to use forge?
I wanna use forge 1.16.5 and it shows that it's not found
![image](https://user-images.githubusercontent.com/47297843/128187918-009b63c4-f56d-4399-9bd6-b4642cf3d2ed.png)

**Comment by KubaTMofficial** [comment]
![image](https://user-images.githubusercontent.com/47297843/128187983-8d4f9a68-2a79-4b1f-9641-fc14f454dd7f.png)

**Comment by AlphaBs** [comment]
```csharp
var versions = await launcher.GetAllVersionsAsync();
foreach (var item in versions)
{
    Console.WriteLine(item.Name);
}
```

this code will show you all installed version name. use this version name

ex
![image](https://user-images.githubusercontent.com/17783561/128203858-fec2b01e-f7ec-4791-9485-9d5a2e88a800.png)
