### ISSUE TITLE
Versions not launching | CmlLib 3.3.1

### ISSUE THREAD

**Issue by SageDevelopment** [CmlLib/CmlLib.Core#31]
Hi there, I've been using CmlLib to create a custom Minecraft Launcher.
I've got everything setup with the UI and the Session Handling but my version wont launch.

This info may help (maybe idk):
- Net Framework 4.7.2 (i dont know if im meant to use a different version possibly?)
- Project Download (full source and stuff): https://easyupload.io/tcyths [new link]
- CmlLib Version: 3.3.1 (Installed from NuGet)
- IDE: Visual Studio 2019 (dont think that would matter)

- Project Type: Windows Forms
- OS: Windows 11
- CPU: Intel Core i7-471OMQ @ 2.50Ghz
- RAM: 16GB
- GPU: Intel HD Graphics 4600 / NVIDIA GTX 860M

In the output when I try to press play, it seems to be doing everything fine but no window shows up.
I also get these in the output:
The thread 0x13f4 has exited with code 0 (0x0).
The thread 0x4380 has exited with code 0 (0x0).
The thread 0x4614 has exited with code 0 (0x0).
The thread 0x42b0 has exited with code 0 (0x0).
The thread 0x984 has exited with code 0 (0x0).
The thread 0x4938 has exited with code 0 (0x0).
The thread 0x2cdc has exited with code 0 (0x0).
The thread 0xeb8 has exited with code 0 (0x0).
The thread 0x28ec has exited with code 0 (0x0).
The thread 0x3a38 has exited with code 0 (0x0).

They kind of seem weird.

I'm hoping that helps resolve this problem!
- Energy

**Comment by AlphaBs** [comment]
is it **ransomware** ? remove exe file

**Comment by AlphaBs** [comment]
### **DO NOT OPEN EXE FILE**

**Comment by SageDevelopment** [comment]
what? wdym exe file?

**Comment by SageDevelopment** [comment]
im confused? i think the site im uploading to may have done something with the link

**Comment by SageDevelopment** [comment]
There i just updated the link and removed the exe file, i think that worked? I hope the new link will work without this "virus? i dont know?"

**Comment by SageDevelopment** [comment]
Hey? Are you okay? Did that file do something to you? I hope it didnt! Im really confused on whats happening...?

**Comment by AlphaBs** [comment]
I'm okay now, I think anonfiles.com inserts some malicious codes...

**Comment by SageDevelopment** [comment]
Oh, wont be using that site again then!

**Comment by SageDevelopment** [comment]
Oh yeah, I think I forgot to put a dependency in that new link called like NewtonSoftJson or something, so I guess I need to update the link again possibly.

**Comment by AlphaBs** [comment]
I'm really sorry for the misunderstanding. I thought you uploaded the malware.

**Comment by SageDevelopment** [comment]
Thats fine, I wonder why anonfiles would add something like that. It used to be really great!

**Comment by SageDevelopment** [comment]
Oh yes, here is the newer link with all the dependencies https://easyupload.io/tcyths

**Comment by M1XT3NZ** [comment]
> 
> 
> Thats fine, I wonder why anonfiles would add something like that. It used to be really great!

it still is great, but if you upload source just upload the source to github.
git is built into visual studio so it should be really easy :)

**Comment by AlphaBs** [comment]
I copied your source code to new .NET framework 4.7.2 winform project, It works well. That's so weired. same source code, but not working..

**Comment by AlphaBs** [comment]
and I found some problems in your code. 

1.  you should use async methods in launchVersion method. `launcher.CreateProcess` might block UI. use `await launcher.CreateProcessAsync`.  

2.  remove `Path = new MinecraftPath(),` in MLaunchOption. [wiki](https://github.com/Cmllib/CmlLib.Core/wiki/MLaunchOption#path)  

3. set event handler before launch. `launcher.FileChanged += ~~~~~` and `launcher.ProgressChanged += ~~~~~` should be done before `launcher.CreateProcess`

```csharp
        public async Task launchVersion(String name)
        {
            var path = new MinecraftPath(); // use default directory
            var launcher = new CMLauncher(path);

            launcher.FileChanged += (fileArgs) =>
            {
                    progressBar1.Maximum = fileArgs.TotalFileCount;
                    progressBar1.Value = fileArgs.ProgressedFileCount;
            };
            launcher.ProgressChanged += (s, progress) =>
            {
                    progressBar2.Maximum = 100;
                    progressBar2.Value = progress.ProgressPercentage;
            };

            var launchOption = new MLaunchOption
            {
                MaximumRamMb = 2048,
                Session = MSession.GetOfflineSession("hi")
            };

            var process = await launcher.CreateProcessAsync(name, launchOption); // vanilla
            process.Start();
        }
```

**Comment by SageDevelopment** [comment]
> I copied your source code to new .NET framework 4.7.2 winform project, It works well. That's so weired. same source code, but not working in your project..

Yeah I find that really strange! I am also using .NET Framework 4.7.2, I'm wondering what is happening. Super crazy!

**Comment by SageDevelopment** [comment]
Could it be that im using Windows 11? As maybe that may be intefering with processes.

**Comment by AlphaBs** [comment]
[WindowsFormsApp1.zip](https://github.com/CmlLib/CmlLib.Core/files/7192467/WindowsFormsApp1.zip)

can you check this project in windows 11?

**Comment by AlphaBs** [comment]
I found that there is no `ICSharpCode.SharpZipLib.dll`, `SevenZip.dll` file in your output directory. remove all nuget packages and reinstall

**Comment by SageDevelopment** [comment]
okay ill try that

**Comment by SageDevelopment** [comment]
Oh god, its working! I'll close this I guess.
