### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pythonblack5000** [CmlLib/CmlLib.Core#37]
Error in https://github.com/CmlLib/CmlLib.Core/wiki/Common-Errors#could-not-create-java-virtual-machine
You write  
"In a 32 bit OS Environment, you can't set MaximumRam(XMX) higher than 1024"
But it's 
For 32-bit Windows: it'll be <2GB (Windows internals book says 2GB for user processes)
For 32-bit BSD / Linux: <3GB (from the Devil Book)
For 32-bit MacOS X: <4GB (from Mac OS X internals book)
(Source: https://stackoverflow.com/a/7019624)

**Logs**
?

**Environment (please complete the following information):**
 - OS: Windows 10
 - CmlLib.Core Version: ?
 - .NET version: ?

(Sorry for my bad english)

**Comment by AlphaBs** [comment]
https://github.com/Cmllib/CmlLib.Core/wiki/Common-Errors
