### ISSUE TITLE
Crash logging

### ISSUE THREAD

**Issue by E4zily** [CmlLib/CmlLib.Core#39]
**Is your feature request related to a problem? Please describe.**
I've always wanted to see why my minecraft crashes, or see the logs in real-time.

**Describe the solution you'd like**
See the game logs in real-time and see them when the game crashes/closes,
and also detect when the game crashes/starts

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fduches** [comment]
Could you tell me if a fix for the forge issue is planned in the upcoming updates?

**Comment by AlphaBs** [comment]
`CreateProcess` method returns `Process` instance. you can read stdout from this.

```csharp
var process = await launcher.CreateProcess(~~~<your codes>~~~);
process.StartInfo.RedirectStandardError = true;
process.StartInfo.RedirectStandardOutput = true;
process.EnableRaisingEvents = true;
process.ErrorDataReceived += (s, e) => Console.WriteLine(e.Data);
process.OutputDataReceived += (s, e) => Console.WriteLine(e.Data);
process.Start();
process.BeginErrorReadLine();
process.BeginOutputReadLine();
```

https://stackoverflow.com/questions/285760/how-to-spawn-a-process-and-capture-its-stdout-in-net

**Comment by AlphaBs** [comment]
I don't have any plan to update forge installer
