### ISSUE TITLE
[BUG] Not working for Forge 1.18

### ISSUE THREAD

**Issue by rex706** [CmlLib/CmlLib.Core#40]
**Describe the bug**

If .minecraft folder is empty, I get the error on first run:
`Could not find a part of the path 'C:\\Users\\USER\\AppData\\Roaming\\.minecraft\\libraries\\net\\minecraftforge\\installertools\\1.2.10\\installertools-1.2.10.jar'.`

On second run after .minecraft folder exists and has some related folders and files, I get:
`Cannot start process because a file name has not been provided.`

I think I tracked this down to being the javaw.exe not being found initially through the JavaChecker class, or there is something wrong with acquiring the forge .jar file. Maybe it is related to the installertools jar?

**Logs**
 Stack Trace for second error: 
 
`at System.Diagnostics.Process.Start() at CmlLib.Utils.ProcessUtil.StartWithEvents() at CmlLib.Core.Installer.MForge.startJava(String[] classpath, String mainclass, String[] args) at CmlLib.Core.Installer.MForge.startProcessor(JToken processor, Dictionary mapData) at CmlLib.Core.Installer.MForge.process(JArray processors, Dictionary mapData) 
at CmlLib.Core.Installer.MForge.InstallForge(String mcversion, String forgeversion) at CmlLib.Core.CMLauncher.CheckForge(String mcversion, String forgeversion, String java) at CmlLib.Core.CMLauncher.CreateProcess(String mcversion, String forgeversion, MLaunchOption option) at 
.......... (local code)"`

This one is resolved by manually providing the Java path, but the game will not open.

**Environment (please complete the following information):**
 - OS: Windows 10
 - CmlLib.Core Version: 3.3.3
 - .NET version: .NET 4.7.2 / 4.8 / 6

**Additional context**

This is how I have been generating my Process:
`Process process = launcher.CreateProcess("1.18", "38.0.10", launchOption);`

First error seems it is not downloading all binaries correctly, but that doesn't seem to stop it on the second run.

Seems as if the algorithm may be having trouble detecting the Java installation, but even when supplied with the direct file path, the game does not open. 

This library was working for me earlier this year on version `3.1.1`, all I had changed was the version of the game and forge that is passed to the launcher.CreateProcess method. 

**The game loads up fine if I omit the Forge version and launch a Vanilla instance.**

EDIT:
Installing Forge manually and using either `CreateProcess` or the updated `CreateProcessAsync` method launches Forge successfully, but won't correctly download and install if it does not already exist, even if the flag for checking and downloading is passed as true just in case.

**Comment by AlphaBs** [comment]
Forge installation feature is deprecated. 

https://github.com/CmlLib/CmlLib.Core/wiki/Forge-Installer
