### ISSUE TITLE
Modpack launcher

### ISSUE THREAD

**Issue by Indoraptor1** [CmlLib/CmlLib.Core#41]
Hello,
How can I make a mod pack launcher like the ftb launcher that has multiple mod packs in the same folder?
Thx for the answer

**Comment by AlphaBs** [comment]
Download mod files and install mod loader like Forge in game directory.

[Download files](https://www.google.com/search?q=C%23+download+file)

[Install forge](https://github.com/CmlLib/CmlLib.Core/wiki/Forge-Installer)
