### ISSUE TITLE
Add Microsoft Login

### ISSUE THREAD

**Issue by GameFusionServers** [CmlLib/CmlLib.Core#43]
Please Add In Microsoft Login And Update The Win Forms To Newest As Had Issues With Username's Having Spaces In

**Comment by GameFusionServers** [comment]
Is WinForms Up To Date?

**Comment by AlphaBs** [comment]
Microsoft Login: [CmlLib.Core.Auth.Microsoft](https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft.UI)

CmlLibWinFormSample is up to date. what does "username's having spaces in" mean?

**Comment by GameFusionServers** [comment]
sorry it was a problem with another dev he was getting bits wrong integrating  into our stuff i shall make sure i report his Facebook marketplace add.... sorry for the confusion
