### ISSUE TITLE
Change client brand

### ISSUE THREAD

**Issue by E4zily** [CmlLib/CmlLib.Core#45]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would love to be able to change the client brand, because some plugins can get your client brand and it would be pretty nice if i could set the brand to something like "Cml Client":
![image](https://user-images.githubusercontent.com/59582293/152655169-288f95f5-bb95-410c-8e3b-e8ad8403593b.png)

**Describe alternatives you've considered**
modifying the version to display a client brand you want

**Additional context**
none

**Comment by AlphaBs** [comment]
This cannot be done with launcher. To change client brand, you should modify game client code. CmlLib.Core does not modify any part of client files.

forge mod:
https://www.curseforge.com/minecraft/mc-mods/brandpacket

fabric mod:
https://www.curseforge.com/minecraft/mc-mods/branding

you can also modify vanilla client file(versions/<version>/<version>.jar) by replacing .class file that set client brand value.

**Comment by E4zily** [comment]
if i try to replace .class file, something replaces the class with the original one, so nothing changes.

**Comment by E4zily** [comment]
also i think you do not quite get it, i talked about client brand packets that the client sends to the server.

**Comment by PolsatGraniePL** [comment]
> **Czy Twoja prośba o funkcję jest związana z problemem? Proszę opisz. ** nie
> 
> **Opisz rozwiązanie, które chciałbyś** , aby móc zmienić markę klienta, ponieważ niektóre wtyczki mogą uzyskać markę klienta i byłoby całkiem miło, gdybym mógł ustawić markę na coś takiego jak "Klient Cml": ![obraz](https://user-images.githubusercontent.com/59582293/152655169-288f95f5-bb95-410c-8e3b-e8ad8403593b.png)
> 
> **Opisz alternatywy, które rozważałeś,** modyfikując wersję, aby wyświetlić wybraną markę klienta
> 
> **Dodatkowy kontekst** brak

ty tutaj robisz launcher, nie clienta... lmao

**Comment by AlphaBs** [comment]
sorry for my late reply

but this can be done in launcher. you should modify client. to prevent replacing the class, remove "downloads" property in version json file.

https://github.com/Cmllib/CmlLib.Core/wiki/FAQ#launch-custom-game-client
