### ISSUE TITLE
System.ArgumentException: 'Invalid Session' 

### ISSUE THREAD

**Issue by rayydev** [CmlLib/CmlLib.Core#48]
When am starting the minecraft (pressing button) am have error : 

System.ArgumentException: 'Invalid Session'

This exception was originally thrown at this call stack:
    [External Code]
    mctest.Program.button1_Click(object, System.EventArgs) in Program.cs

in line of code: `var process = await launcher.CreateProcessAsync("1.8.9", launchOption);`

**Comment by AlphaBs** [comment]
what is the value of `launchOption.Session`? It occurs when the Session has empty value.

**Comment by rayydev** [comment]
> what is the value of `launchOption.Session`? It occurs when the Session has empty value.

Am don`t have in my code launchOption.Session. Am used the example from readme in repo

**Comment by AlphaBs** [comment]
can you show me your code?  
```
var launchOption = new MLaunchOption
{
  // ???
}
```

**Comment by rayydev** [comment]
Am just fixed it. am used that Session = MSession.GetOfflineSession(username) instead of that Session = MSession.GetOfflineSession(textBox1.Text) but thanks for trying me helping!

**Comment by rayydev** [comment]
Am just fixed it. am used that Session = MSession.GetOfflineSession(username) instead of that Session = MSession.GetOfflineSession(textBox1.Text) but thanks for trying me helping!
