### ISSUE TITLE
[BUG] Launching is broken in 1.18

### ISSUE THREAD

**Issue by GEOEGII555** [CmlLib/CmlLib.Core#50]
**Describe the bug**
Launcher is unable to start 1.18 versions. It always says:
![image](https://user-images.githubusercontent.com/57674559/160599880-a4b3967e-051d-4e0d-b1e2-47eb0baf34d2.png)

**Logs**
![image](https://user-images.githubusercontent.com/57674559/160599915-48ef37ee-8871-4655-a1ce-6d43dac88ec0.png)
Java virtual machine start failure

**Environment (please complete the following information):**
 - OS: Windows 10
 - CmlLib.Core Version: 3.3.5
 - .NET version: Visual C# for .NET 6.0

**Comment by AlphaBs** [comment]
can you attach your code? I can't reproduce your error.

**Comment by GEOEGII555** [comment]
`Console.WriteLine("Загрузка файлов (Если они отсутствуют)");
    launcher.FileChanged += (e) =>
    {
        Console.WriteLine("[{0}] {1} - {2}/{3}", e.FileKind.ToString(), e.FileName, e.ProgressedFileCount, e.TotalFileCount);
    };
    var launchOption = new MLaunchOption
    {
        MaximumRamMb = 4096,
        Session = session,

        ScreenWidth = 1600,
        ServerIp = "(removed)"
    };
    var process = await launcher.CreateProcessAsync(ms.Version, launchOption);
    Console.WriteLine("Запуск...");
    process.Start();
    await process.WaitForExitAsync();`

**Comment by PolsatGraniePL** [comment]
> **Describe the bug** Launcher is unable to start 1.18 versions. It always says: ![image](https://user-images.githubusercontent.com/57674559/160599880-a4b3967e-051d-4e0d-b1e2-47eb0baf34d2.png)
> 
> **Logs** ![image](https://user-images.githubusercontent.com/57674559/160599915-48ef37ee-8871-4655-a1ce-6d43dac88ec0.png) Java virtual machine start failure
> 
> **Environment (please complete the following information):**
> 
> * OS: Windows 10
> * CmlLib.Core Version: 3.3.5
> * .NET version: Visual C# for .NET 6.0

nie bug tylko nie ma poprawnie javy zainstalowanej... Aż dziwne ,że mu się normalny minecraft odpala.

**Comment by GEOEGII555** [comment]
> > **Describe the bug** Launcher is unable to start 1.18 versions. It always says: ![image](https://user-images.githubusercontent.com/57674559/160599880-a4b3967e-051d-4e0d-b1e2-47eb0baf34d2.png)
> > **Logs** ![image](https://user-images.githubusercontent.com/57674559/160599915-48ef37ee-8871-4655-a1ce-6d43dac88ec0.png) Java virtual machine start failure
> > **Environment (please complete the following information):**
> > 
> > * OS: Windows 10
> > * CmlLib.Core Version: 3.3.5
> > * .NET version: Visual C# for .NET 6.0
> 
> nie bug tylko nie ma poprawnie javy zainstalowanej... Aż dziwne ,że mu się normalny minecraft odpala.

English please or mods will disable you from commenting

**Comment by PolsatGraniePL** [comment]
use the translator yourself, github is not only english-speaking, it is also open to other countries. And on the wiki, the owner in Chinese can write ... lmao

**Comment by AlphaBs** [comment]
> use the translator yourself, github is not only english-speaking, it is also open to other countries. And on the wiki, the owner in Chinese can write ... lmao

yes you can use any languages on github and no one would block you.

and it's not Chinese, **I'm a korean**

**Comment by PolsatGraniePL** [comment]
> > use the translator yourself, github is not only english-speaking, it is also open to other countries. And on the wiki, the owner in Chinese can write ... lmao
> 
> yes you can use any languages on github and no one would block you.
> 
> and it's not Chinese, **I'm korean**
a, sorry. "weird stamps" are always Chinese XD for most

**Comment by GEOEGII555** [comment]
> yes you can use any languages on github and no one would block you.
Хорошо, буду говорить на русском. Последний ответ был в 2022 году.
