### ISSUE TITLE
process expired

### ISSUE THREAD

**Issue by xss1de** [CmlLib/CmlLib.Core#51]
I'm trying to hide the launcher when the game starts and open it after the game closes, after closing the game the function **process.Exited** doesn't work.

>             var process = await launcher.CreateProcessAsync(startVersion, launchOption);
>             process.Start();
> 
>             this.Hide();
>             process.Exited += (s1, e1) =>
>             {
>                  this.Show();
>             };

**Comment by AlphaBs** [comment]
https://stackoverflow.com/questions/4504170/why-is-my-processs-exited-method-not-being-called


process.EnablRaisingEvents = true;
