### ISSUE TITLE
[BUG] AutoLogin doesn't work with microsoft

### ISSUE THREAD

**Issue by The-Developer-Nate** [CmlLib/CmlLib.Core#52]
**Describe the bug**
If you login using microsoft, autologin doesn't relogin to a microsoft account.

**Logs**
No logs.

**Environment**
 - OS: Windows 11
 - CmlLib.Core Version: 3.3.5
 - .NET version: .NET Framework 4.7.2

**Additional context**
I don't know.

**Comment by M1XT3NZ** [comment]
did you intend to close this?

**Comment by The-Developer-Nate** [comment]
Yes I did because I found the issue.
