### ISSUE TITLE
Cannot find "fabric-loader-0.13.3-1.16.5"

### ISSUE THREAD

**Issue by developerx-official** [CmlLib/CmlLib.Core#55]
**Describe the bug**
When using the following code in version 3.3.5 of CmlLib.Core it throws an exception saying that "fabric-loader-0.13.3-1.16.5" is not found.

```cs
            string fabricName = "fabric-loader-0.13.3-1.16.5";

            // Handle fabric missing
            var fabricVersionLoader = new FabricVersionLoader();
            var fabricVersions = await fabricVersionLoader.GetVersionMetadatasAsync();

            // Install fabric
            if (versions.All(x => x.Name != fabricName))
            {
                try
                {
                    var fabric = fabricVersions.GetVersionMetadata(fabricName);         // Throws error (can't find it)
                    await fabric.SaveAsync(path);

                    // Update version list
                    await launcher.GetAllVersionsAsync();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    Environment.Exit(1);
                }
            }
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - CmlLib.Core Version: 3.3.5
 - .NET version: 6.0-windows

**Additional context**
Occurs for other versions of fabric such as the example in the sample code.

**Comment by Chaniru22** [comment]
I had the same problem and i just noticed that he/they updated the fabric versions so the version is `fabric-loader-0.14.6-1.16.5 `ig

**Comment by developerx-official** [comment]
> I had the same problem and i just noticed that he/they updated the fabric versions so the version is `fabric-loader-0.14.6-1.16.5 `ig

This did not fix my issue, it still does not find fabric.

**Comment by Chaniru22** [comment]
> 

Bruh too late again `fabric-loader-0.14.7-1.16.5`

it updates automatically.
Make sure to check list of versions before telling it
![image](https://user-images.githubusercontent.com/82730163/173229462-749d6256-96b5-4030-aa92-e8ae5921cbcf.png)

**Comment by developerx-official** [comment]
Oh, I see what you mean-the older versions aren't in the metadatas.
Does this mean that obtaining older versions is not supported?

**Comment by Chaniru22** [comment]
> Does this mean that obtaining older versions is not supported?

Yeah you got it ! the way is to keep it alive is get the all metadata and search it (search "1.16.5" for fabric 1.16.5) that's it !
