### ISSUE TITLE
How To Select optifine version

### ISSUE THREAD

**Issue by batuhantrkgl** [CmlLib/CmlLib.Core#57]
how?

**Comment by Chaniru22** [comment]
you can't download and install optifine but you can launch it like others..
for example
![image](https://user-images.githubusercontent.com/82730163/170820259-c4eb0483-2ec5-46a8-8ee5-d964c58ef4ca.png)
the launch version is `1.17.1-OptiFine_HD_U_H1` 

```csharp
var process = launcher.CreateProcess("1.17.1-OptiFine_HD_U_H1", new MLaunchOption
{
    MaximumRamMb = 2048,
    Session = MSession.GetOfflineSession("hello123"),
});
```

(actually its the ID not that)
![image](https://user-images.githubusercontent.com/82730163/170820295-ea68df09-a531-4bc6-a3f5-1b755bf048bf.png)

If you want to download and install optifine,

1. Extract optifine from their default installer
2. Upload the optifine  fles to a your own server
3. Get them from the launcher with some code
