### ISSUE TITLE
[BUG] starts the game with 1.19.1 instead of 1.19

### ISSUE THREAD

**Issue by Ne0N-droid** [CmlLib/CmlLib.Core#60]
https://www.fembed.com/v/177n0ybj7qrjp865
 I showed the error in the link

**Comment by AlphaBs** [comment]
please post your code here

**Comment by Chaniru22** [comment]
I got the same problem. it's not a problem with the cmllib btw

**Comment by Chaniru22** [comment]
![image](https://user-images.githubusercontent.com/82730163/175765645-61aab604-7127-4975-be1f-167f4deca2b0.png)

**Comment by Ne0N-droid** [comment]
> please post your code here

            // Install fabric
            if (!fabricVersions.Any(x => x.Name.Contains("1.18.2")))
            {
                MessageBox.Show("Could not find minecraft version.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                Environment.Exit(1);
            }
            var targetVersions = fabricVersions.Where(x => x.Name.Contains("1.18.2"));
            var fabric = fabricVersions.GetVersionMetadata(targetVersions.First().Name);
            await fabric.SaveAsync(path);
            await launcher.GetAllVersionsAsync();

**Comment by Ne0N-droid** [comment]
![resim](https://user-images.githubusercontent.com/75836325/175766452-e440d6c4-2d04-427e-be64-de53e2bfd01f.png)

**Comment by Chaniru22** [comment]
I got the fix. Use `EndsWith` instead of `Contains`

this is how I do it
```C#
public string SearchFabric(string ver)
        {
            var item = from t in FabricMCVersions where t.Name.EndsWith(ver) select t;
            if (item != null)
            {
                return item.FirstOrDefault().Name;
            }
            else
            {
                return "";
            }
        }
```

**Comment by DerRofocale** [comment]
> 

What is FabricMCVersions? Visual Studion cant to find this namespace

**Comment by MeowNoob** [comment]
lol it's just 
![image](https://user-images.githubusercontent.com/82730163/183586092-14131dff-e218-4de8-98a2-6efe9be06cd2.png)
![image](https://user-images.githubusercontent.com/82730163/183585994-b466dc68-7f12-4c80-b8f7-92a24a474952.png)
btw you don't need to do like that
