### ISSUE TITLE
How to disable multiplayer when launching the Minecraft?

### ISSUE THREAD

**Issue by EvanEvan-17** [CmlLib/CmlLib.Core#61]
I'm trying to make my own launcher with my OWN Parental Control feature, and I'm looking on how to disable multiplayer MANUALLY when launching Minecraft (if parent choose to disable it for their child). Is it possible? Because this is help many parents who don't want their child to play multiplayer on Minecraft, but still want their child to play multiplayer on other games. Because when they change their child's Xbox Account Settings, it will disable multiplayer in MOST Xbox Games.

**Comment by AlphaBs** [comment]
this option is unavailable on current version.

I'll add this feature on next version.

**Comment by evcode17** [comment]
Is this possible? If you can, please make next version immediately

**Comment by evcode17** [comment]
I need this feature, please make it immediately if this is possible, if not possible, then tell me, but IF POSSIBLE, ADD IT NOW! I NEED IT!

**Comment by AlphaBs** [comment]
sorry, I don't have enough time for this project. I think I can start working on it next week.

**Comment by evcode17** [comment]
OK, so just tell me how this is possible? I want to start searching, but you can start working on next week, but please give me how does it possible? I want to know. Thank you.

**Comment by evcode17** [comment]
Can I add that argument to MLaunchOption in JVMArguments property?

**Comment by evcode17** [comment]
`JVMArguments = new string[] { "--disableMultiplayer" }`, this is not working

**Comment by evcode17** [comment]
OK, I have followed the code above, but it is not working, why?

**Comment by evcode17** [comment]
OK, it is now working! THANK YOU VERY MUCH for your help. And it's look like you no longer need to do something, but if you can add this feature directly, then it's good. You can add it to next version in the next week if you don't have a time in this week.

**Comment by TaigoStudio** [comment]
You may need to use authlib-injector using official Mojang servers. I have not tested with the official Mojang server, but with my own authentication server, the online game button is active.
https://github.com/yushijinhun/authlib-injector

**Comment by TaigoStudio** [comment]
@AlphaBs What do you think about this?
