### ISSUE TITLE
How to specify user's private key and public key for Chat Signing and how to handle banned users so they can't play multiplayer when they launch Minecraft with my launcher

### ISSUE THREAD

**Issue by evcode17** [CmlLib/CmlLib.Core#62]
How to specify user's private key and public key for Chat Signing? Is this process automatically or do I have to add some code? And how to disable multiplayer for banned users? Is this process also automatically or do I have to add some code for this? Please answer me so my launcher can comply with Minecraft's current rules, thank you.

**Comment by AlphaBs** [comment]
you don't need to do anything. disabling multiplay, disabling chat, blocked user, everything is handled by minecraft itself.

**Comment by evcode17** [comment]
How the process? What I know is in the Minecraft no online check is performed, so I am confused they are all automatically or not. Is the process for specifying private key or public key is automatically as well?

**Comment by M1XT3NZ** [comment]
Dude everything is handled by Mojang INTERNALLY
it has nothing todo with the client. 
also these new rules are garbage anyway so

**Comment by evcode17** [comment]
Yes, I understand that some people don't like it, but you HAVE to follow it to play Minecraft. Your only option is follow it or stop playing it.

**Comment by AlphaBs** [comment]
Minecraft do checks user's access token. It makes 3 requests using user's access token:

1. /player/attributes
request on startup to check if the user is allowed to do chat, multiplay server, multiplay realms and send telemetry. also set 'profanityFilterPreferences'.

2. /privacy/blocklist
When the minecraft client receives an chatting message, it requests here to check if the message is from blocked user.

3. /player/certificates
When the minecraft connects to the online server, it request here to get chatting certificates.

I decompiled Minecraft 1.19 using MCP and checked it by myself.

**Comment by evcode17** [comment]
Thank you! How to decompile Minecraft using MCP?

**Comment by AlphaBs** [comment]
I used [MCP-Reborn](https://github.com/Hexeption/MCP-Reborn)

**Comment by evcode17** [comment]
When I decode it using MCP, may I use the source code to make my own published client?

**Comment by AlphaBs** [comment]
I don't know well about license

maybe you can't publish any code from mcp.
