### ISSUE TITLE
Does this library automatically install Java if user don't have one?

### ISSUE THREAD

**Issue by evcode17** [CmlLib/CmlLib.Core#64]
Does this library automatically install Java if user don't have one? Because many launcher (even the official launcher) do this. If this library doesn't currently handle this, then please make it.

**Comment by M1XT3NZ** [comment]
[Link to How its done and technically you shouldve found that out by yourself by just reading the wiki or reading any documentation at all ;) ](https://github.com/CmlLib/CmlLib.Core/blob/master/CmlLibWinFormSample/MainForm.cs#L282)

**Comment by AlphaBs** [comment]
It automatically installs java. 


on the latest version you don't even need to use `MJava`.

**Comment by evcode17** [comment]
So I don't need to do anything?

**Comment by AlphaBs** [comment]
yes
