### ISSUE TITLE
[BUG] Custom Path isnt working

### ISSUE THREAD

**Issue by Pruzah** [CmlLib/CmlLib.Core#71]
![image](https://user-images.githubusercontent.com/111691645/208642957-3a85a29b-36a2-4ae9-b503-230b7f730b9c.png)
![image](https://user-images.githubusercontent.com/111691645/208642981-b5e4baef-6ee7-47ad-8ef6-3df6bb08bafe.png)
![image](https://user-images.githubusercontent.com/111691645/208643054-ea86c9d0-3edc-468f-9b38-434093496ff5.png)
if my wrong pls help me

**Comment by mzggr0914** [comment]
%appdata%is Environment.SpecialFolder.ApplicationData

**Comment by Pruzah** [comment]
I new on codding help me how fix this

**Comment by NoobNotFound** [comment]
> I new on codding help me how fix this

```C#
var basePath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\pokebalta";
var myPath = new MinecraftPath(basePath);
```
Other rest of the properties is not necessary I think.
