### ISSUE TITLE
(Question) some questions to answer

### ISSUE THREAD

**Issue by Foreverably** [CmlLib/CmlLib.Core#72]
I want to see if its possible to change the minecraft title bar text and close the logs when minecraft is closed (unless im dumb). i have checked the source and i have not seen it at all

**Comment by NoobNotFound** [comment]
>close the logs when minecraft is closed

what do you actually mean by this?
well, if I got you right you can dispose the process like this (kinda unnecessary)
```C#
process.Exited += (_, _) => process.Dispose();
```
or
```C#
await process.WaitForExitAsync();
process.Dispose();
```

**Comment by Foreverably** [comment]
> > close the logs when minecraft is closed
> 
> what do you actually mean by this? well, if I got you right you can dispose the process like this (kinda unnecessary)
> 
> ```cs
> process.Exited += (_, _) => process.Dispose();
> ```
> 
> or
> 
> ```cs
> await process.WaitForExitAsync();
> process.Dispose();
> ```

This will work :>
