### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ahmed3457** [CmlLib/CmlLib.Core#75]
**Describe the bug**
an error message is shown at start up
![image](https://user-images.githubusercontent.com/93637332/212382515-6de45bb5-cc3a-45fb-bdfa-098bbd3eb56f.png)

**Logs**
If applicable, add log file to help explain your problem. log file location: `<game_directory>/logs/latest.log`

**Environment (please complete the following information):**
 - OS: Windows 7
 - CmlLib.Core Version: Latest
 - .NET version: 4.7

**Additional context**

**Comment by Ahmed3457** [comment]
btw i was using the example launcher provided in the latest release

**Comment by rudde0** [comment]
Could you try again with this changes:
```
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by AlphaBs** [comment]
Old Windows does not support latest TLS/SSL connection. 

Especially Windows 7 users often experience this error. It can be solved by just running Windows update.
