### ISSUE TITLE
Minecraft Crash problem[BUG]

### ISSUE THREAD

**Issue by KaanCK** [CmlLib/CmlLib.Core#76]
When the play button on the launcher is pressed, the game opens and closes for 1 second and the game does not start, then such a log is created.

**Logs**
[crash-2023-01-16_18.53.20-client.txt](https://github.com/CmlLib/CmlLib.Core/files/10428302/crash-2023-01-16_18.53.20-client.txt)

**Environment (please complete the following information):**
 - OS: Windows 11
 - CmlLib.Core Version: Latest Version
 - .NET version: 4.7.2

**Comment by rudde0** [comment]
https://github.com/CmlLib/CmlLib.Core/pull/77 fixed this issue

**Comment by AlphaBs** [comment]
use 3.3.6
