### ISSUE TITLE
Little mistake in the wiki [BUG]

### ISSUE THREAD

**Issue by zylonity** [CmlLib/CmlLib.Core#78]
Hi! Sorry if this isn't a mistake, I could be the one that's wrong but on

wiki -> CMLauncher -> Basic Usage - Async version

when the process is created in the example, it's using "launcher.CreateProcess()" instead of  "launcher.CreateProcessAsync()", which causes a problem with the await operator

**Comment by AlphaBs** [comment]
fixed
