### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by semihofc** [CmlLib/CmlLib.Core#80]
I forked the sample project and changed the design little bit (didnt touched code)

Issue:
When i try to start Optifine 1.16.5 (local custom) it loads and gives Game Crashed log
Crash logs:
[crash-2023-01-31_20.35.41-client.txt](https://github.com/CmlLib/CmlLib.Core/files/10549760/crash-2023-01-31_20.35.41-client.txt)
[crash-2023-01-31_20.33.15-client.txt](https://github.com/CmlLib/CmlLib.Core/files/10549761/crash-2023-01-31_20.33.15-client.txt)
I'm new to these and since i dont really know Java, i dont know what is this issue

**Comment by semihofc** [comment]
Update: looks like it can run vanilla 1.16.5 after i download via launcher but it cant load my optifine 1.16.5 which i installed before with TLauncher

**Comment by PoligamerYT** [comment]
Can you send the code pls

**Comment by AlphaBs** [comment]
#16

TLauncher has quite different version json structure.

**Comment by semihofc** [comment]
Oh so if i install Optifine gl seperately it will work?

**Comment by semihofc** [comment]
Need to install optifine seperately because of other launchers' json format
