### ISSUE TITLE
Minecraft Blocking different launchers ?

### ISSUE THREAD

**Issue by BunyaminEfe** [CmlLib/CmlLib.Core#86]
How can I prevent it from coming over different clients when logging into the minecraft server in c# Java can also be done here, but c# can you help?  
![image](https://github.com/CmlLib/CmlLib.Core/assets/30906513/74e9b4b9-2e9b-41f7-b2d9-901cd0f128ab)

**Comment by BasicallyWiz** [comment]
I think your problem is the in-server authentication. Even if you launch Minecraft from different launchers, if you try to join a single server twice with the same account at once, the server will drop or refuse the connection to one of the clients.

There is no fix, buy a second account.
