### ISSUE TITLE
[BUG] Direct connect on server not working on 1.20.1

### ISSUE THREAD

**Issue by sniper95260** [CmlLib/CmlLib.Core#89]
Hello,

I have an issue when trying to connect directly to a server.

It worked fine on a 1.19.2 server, but i updated it to 1.20.1 and now, when i try to launch the game and auto connect, It launch and go to the minecraft main screen, no error or anything. Tried with both server name and server IP with the same results.

My MLaunchOption seems good, other parameters works well (Session, FullScreen, MinimumRamMb etc), and my ServerIp and ServerPort are correctly set.

Here's the method I use to prepare and launch the game :

![image](https://github.com/CmlLib/CmlLib.Core/assets/55689019/38e4791a-3460-402e-9336-657922e68a47)

Is this a known issue or is there something I missed ?

Thank you for your help.

**Environment:**
 - OS: Launcher on Windows 10 / Server on Debian
 - Minecraft/Forge version : 1.20.1 / 47.2.0
 - CmlLib.Core Version: 3.3.7
 - CmlLib.Core.Auth.Microsoft Version: 3.0.1
 - CmlLib.Core.Installer.Forge Version: 0.0.2
 - .NET version: .NET 5.0

**Comment by AlphaBs** [comment]
the parameter for server connecting have been updated since 1.20. this will be fixed soon

**Comment by sniper95260** [comment]
Thank you for the fast reply :) 

Is there any workaround i can implement until this fix ? Maybe a java argument or something ?

**Comment by NoThrottle** [comment]
any ETA on this?

**Comment by AlphaBs** [comment]
3.3.9 released
