### ISSUE TITLE
[Bug] Multiplayer is disabled in 1.16.6

### ISSUE THREAD

**Issue by ugivvvv** [CmlLib/CmlLib.Core#91]
Multiplayer is disabled in 1.16.5

Environment
 - OS: [e.g. Windows 10]
 - CmlLib.Core Version: [e.g. 3.3.8]

I have created my own launcher, but I can't play multiplayer in version 1.16.5. The multiplayer button and realms button are dark gray, and when I try to click, the following message appears: 'Multiplayer is disabled. Please check your Microsoft account.' I am sure there is no error in the code.

**Comment by AlphaBs** [comment]
please show me your code. did you use offline session?

**Comment by WorldHim** [comment]
in 1.16.4/5, if you use offline session, multiplayer will be disabled.

**Comment by WorldHim** [comment]
in 1.16.4/5, if you use offline session, multiplayer will be disabled.

**Comment by AlphaBs** [comment]
see #85
