### ISSUE TITLE
Change game directory in launch options

### ISSUE THREAD

**Issue by sk8teeee** [CmlLib/CmlLib.Core#92]
I'm fursutrated when I cant change my game launch directory.

MLaunchOption add string prameter to set game directory. 
Like in normal launcher edit installation
![Bild_2024-01-21_132523477](https://github.com/CmlLib/CmlLib.Core/assets/87061904/4025205f-7250-416d-9b0c-81cad483d6d6

**Comment by AlphaBs** [comment]
https://alphabs.gitbook.io/cmllib/cmllib.core/getting-started/minecraftpath
