### ISSUE TITLE
[BUG]

When i provide server ip and port for auto connect to server on startup, the background does not load in 1.16.5 OptiFine

### ISSUE THREAD

**Issue by MeteBhey** [CmlLib/CmlLib.Core#93]
It says **Failed to load texture: minecraft:textures/gui/options_background.png** in latest.log

 - OS: Windows 11
 - CmlLib.Core Version: 3.3.8
 - .NET version: .NET Framework 4.6.2, .NET 6.0

**Comment by AlphaBs** [comment]
Unfortunately, It seems OptiFine's bug. we can't fix.

**Comment by MeteBhey** [comment]
But if I dont use auto connect the background is normal

**Comment by AlphaBs** [comment]
you may need to modify optifine to fix this

**Comment by MeteBhey** [comment]
I tried it. It says it can't find the file in path but the file is in path
