### ISSUE TITLE
Cancellation support for async launcher methods

### ISSUE THREAD

**Issue by dumbdeniz** [CmlLib/CmlLib.Core#95]
add optional cancellationToken parameter for async launcher methods like `CheckLostGameFilesTaskAsync` and `CheckAndDownloadAsync` so these long running operations can be cancelled by the user. (if they wanted to abort the process)

These methods sometimes take long to complete with slower computers and network speeds. The library supporting cancellation for these methods could help users cancel the launching process if they wish to, like if they changed their mind & want to select a different version for example.

If thats ok, i'll work on a PR adding this.

**Comment by AlphaBs** [comment]
I'm working on v3.4.0 branch. it has CancellationToken supports.

**Comment by dumbdeniz** [comment]
Thats great! i see major changes on that branch, when do you plan on merging it?

**Comment by AlphaBs** [comment]
maybe within 3 months? at least I can publish pre-release version
