### ISSUE TITLE
Mac silicon compatibility

### ISSUE THREAD

**Issue by Mixgyt** [CmlLib/CmlLib.Core#96]
Hello, I was reviewing the code to handle the installation of java, but I still want to clarify a question, can download the version of java for mac silicon?

in advance good day

**Comment by AlphaBs** [comment]
Current version (3.3.9) would not install arm version of java. I implemented this on 'v3.4.0' branch but I haven't test yet (I don't have mac)

**Comment by Mixgyt** [comment]
Ok, So I'll try it with my mac.
