### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MehanikTMYT** [CmlLib/CmlLib.Core#97]
**Describe the bug**
Dosn't launch any version of forge (or NeoForge) above 1.20.1 even if it started sucesefully in official launcher without downloading any file (insted of Cmllib.Core) and no any logs with errors or something like in Visual Studio (for example forge 1.20.1 started without errors)

**Environment (please complete the following information):**
 - OS: Windows 11 
 - CmlLib.Core Version: Latest - 3.3.9

**Comment by AlphaBs** [comment]
please attach `game_directory/logs/latest.log` file.

**Comment by MehanikTMYT** [comment]
files from client - http://92.255.108.96/ftb/1.20.4-neo/assets.zip http://92.255.108.96/ftb/1.20.4-neo/libraries.zip http://92.255.108.96/ftb/1.20.4-neo/versions.zip (all from my VDS)

**Comment by MehanikTMYT** [comment]
sorry for my stupid thing. This is log 06.03.2024 23:32:41 - Exception in thread "main" java.lang.IllegalStateException: Duplicate key D:\Загрузки\1.20.4-forge\games\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar (attempted merging values EmbeddedFileSystemMetadata[path=D:\Загрузки\1.20.4-forge\games\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar, fs=D:\Загрузки\1.20.4-forge\games\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar, fsCh=sun.nio.ch.FileChannelImpl@1ed1993a] and EmbeddedFileSystemMetadata[path=D:\Загрузки\1.20.4-forge\games\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar, fs=D:\Загрузки\1.20.4-forge\games\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar, fsCh=sun.nio.ch.FileChannelImpl@1f3f4916])
06.03.2024 23:32:41 - 	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
06.03.2024 23:32:41 - 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
06.03.2024 23:32:41 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
06.03.2024 23:32:41 - 	at cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:140)
06.03.2024 23:32:41 - 	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:120)
06.03.2024 23:32:41 - 	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:101)
06.03.2024 23:32:41 - 	at cpw.mods.jarhandling.impl.Jar.newFileSystem(Jar.java:216)
06.03.2024 23:32:41 - 	at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:89)
06.03.2024 23:32:42 - 	at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:73)
06.03.2024 23:32:42 - 	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:64)
06.03.2024 23:32:42 - 	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:60)
06.03.2024 23:32:42 - 	at net.minecraftforge.bootstrap.ClassPathHelper.getCleanedClassPathImpl(ClassPathHelper.java:178)
06.03.2024 23:32:42 - 	at net.minecraftforge.bootstrap.ClassPathHelper.getCleanedClassPath(ClassPathHelper.java:46)
06.03.2024 23:32:42 - 	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:28)
06.03.2024 23:32:42 - 	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18)

**Comment by MehanikTMYT** [comment]
how to fix?

**Comment by MehanikTMYT** [comment]
if try to start neoforge 1.20.4 -  Exception in thread "main" java.lang.IllegalStateException: Duplicate key D:\Загрузки\neoforge-20.4.194\games\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar (attempted merging values EmbeddedFileSystemMetadata[path=D:\Загрузки\neoforge-20.4.194\games\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar, fs=D:\Загрузки\neoforge-20.4.194\games\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar, fsCh=sun.nio.ch.FileChannelImpl@6580cfdd] and EmbeddedFileSystemMetadata[path=D:\Загрузки\neoforge-20.4.194\games\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar, fs=D:\Загрузки\neoforge-20.4.194\games\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar, fsCh=sun.nio.ch.FileChannelImpl@7e0b85f9])
07.03.2024 11:47:09 - 	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
07.03.2024 11:47:09 - 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
07.03.2024 11:47:09 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:138)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:117)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:107)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.JarContentsImpl.<init>(JarContentsImpl.java:55)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:35)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:212)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:196)
07.03.2024 11:47:10 - 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:180)
07.03.2024 11:47:10 - 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.lambda$main$6(BootstrapLauncher.java:99)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
07.03.2024 11:47:10 - 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
07.03.2024 11:47:10 - 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:93)

**Comment by MehanikTMYT** [comment]
i wait for answer

**Comment by AlphaBs** [comment]
sorry for the delay. I'm investigating the issue now.

**Comment by AlphaBs** [comment]
fixed 0ce9e39

update to 3.3.10
